<div style="float: right; margin-left: 10px;"  data-bind="scope: 'hobbyUiComponent'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "hobbyUiComponent": {
                        "component": "Zaproo_Hobby/js/hobby",
                        "config": {
                            "template": "Zaproo_Hobby/hobby"
                        }
                    }
                }
            }
        }
    }
</script>
